[[redirects]]
from= "/*"
to = "/index.html"
status = 200


[[redirects]]
  from = "/api/student/*"
  to = "https://nmims-placement-portal.vercel.app/api/student/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
